name: Build User Script

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create build directory
        run: mkdir -p build
      
      - name: Copy and rename script
        run: cp main.js build/main.user.js
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: user-script
          path: build/main.user.js